server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-173.railway.app:7353/railway
    username: postgres
    password: QuD8Oh894DIAU86flFYt
    drive-class-name: org.postgresql.Driver
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/test_app
#    username: postgres
#    password: root123
#    drive-class-name: org.postgresql.Driver
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always